services:
    db:
        image: postgres:17.6
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 10s
            timeout: 3s
            retries: 3
    etl:
        build:
            context: .
        env_file:
            - .env
        container_name: vk-test-task
        image: app/vk-test-task:latest
        restart: "always"
        stop_signal: SIGINT
        volumes:
            - logs:/app/logs
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    logs: